name: Echo GitHub Context and Environment Variables

on:
  push:
  workflow_dispatch:

env:
  GLOBAL_VAR: "This is a global environment variable"

jobs:
  echo-context:
    runs-on: ubuntu-latest
    
    env:
      JOB_VAR: "This is a job-level environment variable"
    
    steps:
      - name: Echo GitHub Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"

      - name: Echo Environment Variables
        run: |
          echo "Global Var: $GLOBAL_VAR"
          echo "Job Var: $JOB_VAR"
