name: Push to Specific Branch

on:
  push:
    branches:
      - 'main'        # Trigger on pushes to the 'main' branch
      - 'feature/*'   # Trigger on pushes to any branch starting with 'feature/'
