name: Node.js CI on Self-Hosted Runner

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Display Node.js version
        run: node --version

      - name: Check self-hosted runner details
        run: |
          echo "Self-hosted runner details:"
          uname -a
          whoami
